[tool.pylint.main]

# Allow loading of arbitrary C extensions. Extensions are imported into the
# active Python interpreter and may run arbitrary code.
unsafe-load-any-extension = true

# Limit actions to using 1 core per action.
jobs = 1

# Lints to explicitly disable
disable = []
