load("//python:defs.bzl", "py_library")
load("//python/mypy:defs.bzl", "py_mypy_test")

py_library(
    name = "sidecar",
    srcs = ["sidecar/__init__.py"],
    data = ["sidecar/py.typed"],
    imports = ["."],
    visibility = ["//python/mypy/private/tests:__subpackages__"],
)

py_mypy_test(
    name = "sidecar_mypy_test",
    target = ":sidecar",
)
